name=input("enter name: ")
age=int(input("age: "))
Father=input("enter father's name: ")
mother=input("enter mother's name: ")
hobby=input("enter hobby: ")
nationality=input("enter nationality: ") 
DOB=input("enter date of birth: ")
school_name=input("school name: ")
collage=input("enter collage name: ")
university=input("enter university name: ")
course=input("enter the name of the course: ")
print (name)
print(age)
print(Father)
print(mother)
print(hobby)
print(nationality)
print(DOB)
print(school_name)
print(collage)
print(university)
print(course)